## Using Logistic Regression

### import relevant libraries 

In [1]:
import pandas as pd
import numpy as np

In [2]:
## importing preprocessed data
data_preprocessed = pd.read_csv("df_preprocessed.csv")
data_preprocessed.head()

reason_type_1  reason_type_2  reason_type_3  reason_type_4  Month value  \
0              0              0              0              1            7   
1              0              0              0              0            7   
2              0              0              0              1            7   
3              1              0              0              0            7   
4              0              0              0              1            7   

   Day of week  Transportation Expense  Distance to Work  Age  \
0            1                     289                36   33   
1            1                     118                13   50   
2            2                     179                51   38   
3            3                     279                 5   39   
4            3                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          0         2     1   
1                  239.554               31          0         1     0   
2                  239.554               31          0         0     0   
3                  239.554               24          0         2     0   
4                  239.554               30          0         2     1   

   Absenteeism Time in Hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2

### Creating Targets for Logistic Regression

In [3]:
data_preprocessed["Absenteeism Time in Hours"].median()

3.0

In [4]:
targets= np.where(data_preprocessed["Absenteeism Time in Hours"]>
                data_preprocessed["Absenteeism Time in Hours"].median(),1,0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [5]:
data_preprocessed["Excessive Absenteeism"]=targets
data_preprocessed.head()

reason_type_1  reason_type_2  reason_type_3  reason_type_4  Month value  \
0              0              0              0              1            7   
1              0              0              0              0            7   
2              0              0              0              1            7   
3              1              0              0              0            7   
4              0              0              0              1            7   

   Day of week  Transportation Expense  Distance to Work  Age  \
0            1                     289                36   33   
1            1                     118                13   50   
2            2                     179                51   38   
3            3                     279                 5   39   
4            3                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          0         2     1   
1                  239.554               31          0         1     0   
2                  239.554               31          0         0     0   
3                  239.554               24          0         2     0   
4                  239.554               30          0         2     1   

   Absenteeism Time in Hours  Excessive Absenteeism  
0                          4                      1  
1                          0                      0  
2                          2                      0  
3                          4                      1  
4                          2                      0

In [6]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours'],axis=1)
data_with_targets.head()

reason_type_1  reason_type_2  reason_type_3  reason_type_4  Month value  \
0              0              0              0              1            7   
1              0              0              0              0            7   
2              0              0              0              1            7   
3              1              0              0              0            7   
4              0              0              0              1            7   

   Day of week  Transportation Expense  Distance to Work  Age  \
0            1                     289                36   33   
1            1                     118                13   50   
2            2                     179                51   38   
3            3                     279                 5   39   
4            3                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          0         2     1   
1                  239.554               31          0         1     0   
2                  239.554               31          0         0     0   
3                  239.554               24          0         2     0   
4                  239.554               30          0         2     1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [7]:
## selecting inputs
unscaled_inputs = data_with_targets.iloc[:,:-1]
unscaled_inputs

reason_type_1  reason_type_2  reason_type_3  reason_type_4  Month value  \
0                0              0              0              1            7   
1                0              0              0              0            7   
2                0              0              0              1            7   
3                1              0              0              0            7   
4                0              0              0              1            7   
..             ...            ...            ...            ...          ...   
695              1              0              0              0            5   
696              1              0              0              0            5   
697              1              0              0              0            5   
698              0              0              0              1            5   
699              0              0              0              1            5   

     Day of week  Transportation Expense  Distance to Work  Age  \
0              1                     289                36   33   
1              1                     118                13   50   
2              2                     179                51   38   
3              3                     279                 5   39   
4              3                     289                36   33   
..           ...                     ...               ...  ...   
695            2                     179                22   40   
696            2                     225                26   28   
697            3                     330                16   28   
698            3                     235                16   32   
699            3                     291                31   40   

     Daily Work Load Average  Body Mass Index  Education  Children  Pets  
0                    239.554               30          0         2     1  
1                    239.554               31          0         1     0  
2                    239.554               31          0         0     0  
3                    239.554               24          0         2     0  
4                    239.554               30          0         2     1  
..                       ...              ...        ...       ...   ...  
695                  237.656               22          1         2     0  
696                  237.656               24          0         1     2  
697                  237.656               25          1         0     0  
698                  237.656               25          1         0     0  
699                  237.656               25          0         1     1  

[700 rows x 14 columns]

### Standardize The Input

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
absenteeism_scaler = StandardScaler()

In [10]:
unscaled_inputs.columns.values

array(['reason_type_1', 'reason_type_2', 'reason_type_3', 'reason_type_4',
       'Month value', 'Day of week', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets'], dtype=object)

In [11]:
absenteeism_scaler.fit(unscaled_inputs[['Month value', 'Day of week', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets']])

StandardScaler()

In [12]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs[['Month value', 'Day of week', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets']])
scaled_inputs

array([[ 0.18272635, -0.68370352,  1.00584437, ..., -0.44798003,
         0.88046927,  0.26848661],
       [ 0.18272635, -0.68370352, -1.57468098, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [ 0.18272635, -0.00772546, -0.6541427 , ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [-0.3882935 ,  0.66825259,  1.62456682, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.3882935 ,  0.66825259,  0.19094163, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.3882935 ,  0.66825259,  1.03602595, ..., -0.44798003,
        -0.01928035,  0.26848661]])

In [13]:
df_normalized = pd.DataFrame(scaled_inputs,columns=['Month value', 'Day of week', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets'])
df_normalized = df_normalized.join(unscaled_inputs[unscaled_inputs.columns.drop(['Month value', 'Day of week', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets'])])
columns_reorder = ['reason_type_1', 'reason_type_2', 'reason_type_3', 'reason_type_4',
       'Month value', 'Day of week', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets']
df_normalized = df_normalized[columns_reorder]

### Split into Train and Test Data's

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df_normalized,targets,train_size = 0.8, random_state=20)
print(x_train.shape,y_train.shape)
print(x_test.shape,y_test.shape)

(560, 14) (560,)
(140, 14) (140,)


### using Sklearn for Logistic Regression

In [15]:
from sklearn.linear_model import LogisticRegression

In [16]:
reg=LogisticRegression()

In [17]:
reg.fit(x_train,y_train)

LogisticRegression()

In [18]:
reg.score(x_train,y_train)

0.7785714285714286

### Manually calculating accuracy

In [19]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [20]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [21]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [22]:
#getting correct output for this many inputs
correct_prediction =np.sum((model_outputs==y_train))

In [23]:
# total no of inputs
total=model_outputs.shape[0]

In [24]:
manual_accuracy = correct_prediction/total
manual_accuracy

0.7785714285714286

### Intercepts and Coefficients

In [25]:
reg.intercept_

array([-1.68969191])

In [26]:
reg.coef_

array([[ 2.80088908e+00,  9.37679263e-01,  3.09784623e+00,
         8.55189097e-01,  1.65600560e-01, -8.38855532e-02,
         6.13417431e-01, -9.52263740e-03, -1.66485910e-01,
        -9.39188259e-04,  2.69858214e-01, -8.32092336e-02,
         3.60649946e-01, -2.86053551e-01]])

In [27]:
feature_names=unscaled_inputs.columns.values

In [28]:
summary_table = pd.DataFrame(columns = ["features"],data= feature_names)
summary_table["coefficient"]=np.transpose(reg.coef_)
summary_table

features  coefficient
0             reason_type_1     2.800889
1             reason_type_2     0.937679
2             reason_type_3     3.097846
3             reason_type_4     0.855189
4               Month value     0.165601
5               Day of week    -0.083886
6    Transportation Expense     0.613417
7          Distance to Work    -0.009523
8                       Age    -0.166486
9   Daily Work Load Average    -0.000939
10          Body Mass Index     0.269858
11                Education    -0.083209
12                 Children     0.360650
13                     Pets    -0.286054

In [29]:
summary_table.index = summary_table.index+1
summary_table.loc[0]=['Intercept',reg.intercept_[0]]
summary_table

features  coefficient
1             reason_type_1     2.800889
2             reason_type_2     0.937679
3             reason_type_3     3.097846
4             reason_type_4     0.855189
5               Month value     0.165601
6               Day of week    -0.083886
7    Transportation Expense     0.613417
8          Distance to Work    -0.009523
9                       Age    -0.166486
10  Daily Work Load Average    -0.000939
11          Body Mass Index     0.269858
12                Education    -0.083209
13                 Children     0.360650
14                     Pets    -0.286054
0                 Intercept    -1.689692

In [30]:
summary_table = summary_table.sort_index()
summary_table

features  coefficient
0                 Intercept    -1.689692
1             reason_type_1     2.800889
2             reason_type_2     0.937679
3             reason_type_3     3.097846
4             reason_type_4     0.855189
5               Month value     0.165601
6               Day of week    -0.083886
7    Transportation Expense     0.613417
8          Distance to Work    -0.009523
9                       Age    -0.166486
10  Daily Work Load Average    -0.000939
11          Body Mass Index     0.269858
12                Education    -0.083209
13                 Children     0.360650
14                     Pets    -0.286054

### Interpreting the coefficient

In [31]:
summary_table["odds_ratio"]=np.exp(summary_table.coefficient)
summary_table.sort_values(['odds_ratio'],ascending = False)

features  coefficient  odds_ratio
3             reason_type_3     3.097846   22.150193
1             reason_type_1     2.800889   16.459274
2             reason_type_2     0.937679    2.554047
4             reason_type_4     0.855189    2.351819
7    Transportation Expense     0.613417    1.846732
13                 Children     0.360650    1.434261
11          Body Mass Index     0.269858    1.309779
5               Month value     0.165601    1.180102
10  Daily Work Load Average    -0.000939    0.999061
8          Distance to Work    -0.009523    0.990523
12                Education    -0.083209    0.920159
6               Day of week    -0.083886    0.919536
9                       Age    -0.166486    0.846635
14                     Pets    -0.286054    0.751222
0                 Intercept    -1.689692    0.184576

### Testing the model

In [32]:
reg.score(x_test,y_test)

0.7428571428571429

In [33]:
predict_probalilities = reg.predict_proba(x_test)
predict_probalilities

array([[0.73864053, 0.26135947],
       [0.60789646, 0.39210354],
       [0.40996973, 0.59003027],
       [0.80472183, 0.19527817],
       [0.07323255, 0.92676745],
       [0.31941804, 0.68058196],
       [0.31226346, 0.68773654],
       [0.13306856, 0.86693144],
       [0.79635128, 0.20364872],
       [0.75286427, 0.24713573],
       [0.48231604, 0.51768396],
       [0.19563399, 0.80436601],
       [0.07839777, 0.92160223],
       [0.7089873 , 0.2910127 ],
       [0.30548379, 0.69451621],
       [0.57237284, 0.42762716],
       [0.54122481, 0.45877519],
       [0.57229528, 0.42770472],
       [0.38058499, 0.61941501],
       [0.04846973, 0.95153027],
       [0.69721698, 0.30278302],
       [0.79565677, 0.20434323],
       [0.39396853, 0.60603147],
       [0.42134577, 0.57865423],
       [0.26457608, 0.73542392],
       [0.75562849, 0.24437151],
       [0.50913803, 0.49086197],
       [0.86909265, 0.13090735],
       [0.20199742, 0.79800258],
       [0.78628266, 0.21371734],
       [0.

In [37]:
# probabilities of getting output as 1 for each test cases.
predict_probalilities[:,1]

array([0.26135947, 0.39210354, 0.59003027, 0.19527817, 0.92676745,
       0.68058196, 0.68773654, 0.86693144, 0.20364872, 0.24713573,
       0.51768396, 0.80436601, 0.92160223, 0.2910127 , 0.69451621,
       0.42762716, 0.45877519, 0.42770472, 0.61941501, 0.95153027,
       0.30278302, 0.20434323, 0.60603147, 0.57865423, 0.73542392,
       0.24437151, 0.49086197, 0.13090735, 0.79800258, 0.21371734,
       0.37452257, 0.68766232, 0.68796537, 0.54119832, 0.20434323,
       0.50832445, 0.21159766, 0.74567523, 0.43659552, 0.59038172,
       0.22486786, 0.4329032 , 0.21773306, 0.39322396, 0.81383409,
       0.5728771 , 0.69394041, 0.27227748, 0.20330526, 0.1805275 ,
       0.59007004, 0.34373418, 0.66750008, 0.28651451, 0.85008643,
       0.47081844, 0.8896698 , 0.25693654, 0.31951243, 0.31761548,
       0.71999198, 0.65734268, 0.31267685, 0.78843857, 0.19876603,
       0.26513822, 0.08248999, 0.23097525, 0.72914791, 0.33153852,
       0.21144752, 0.29592047, 0.90899949, 0.43882513, 0.61971

### Save the Model

In [38]:
import pickle
with open('model','wb') as file:
    pickle.dump(reg,file)

In [39]:
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler,file)